In [8]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy as np


In [11]:
a=(1,2)
np.array(a)


array([1, 2])

In [12]:
np.arange(2)

array([0, 1])

In [13]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
np.arange(1,80,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.linspace(3,4)

array([3.        , 3.02040816, 3.04081633, 3.06122449, 3.08163265,
       3.10204082, 3.12244898, 3.14285714, 3.16326531, 3.18367347,
       3.20408163, 3.2244898 , 3.24489796, 3.26530612, 3.28571429,
       3.30612245, 3.32653061, 3.34693878, 3.36734694, 3.3877551 ,
       3.40816327, 3.42857143, 3.44897959, 3.46938776, 3.48979592,
       3.51020408, 3.53061224, 3.55102041, 3.57142857, 3.59183673,
       3.6122449 , 3.63265306, 3.65306122, 3.67346939, 3.69387755,
       3.71428571, 3.73469388, 3.75510204, 3.7755102 , 3.79591837,
       3.81632653, 3.83673469, 3.85714286, 3.87755102, 3.89795918,
       3.91836735, 3.93877551, 3.95918367, 3.97959184, 4.        ])

In [34]:
np.random.randn(40,42)

array([[ 0.97639491,  0.33571344,  1.5203863 , ..., -0.40051825,
         0.2670068 , -0.3568451 ],
       [ 0.12491844,  0.69155679,  0.24528672, ..., -1.29536925,
        -1.62067516, -0.64294732],
       [ 0.45285361, -0.11839236, -1.27028231, ...,  0.09644795,
         0.32467612,  0.60541017],
       ...,
       [-1.33588661,  1.00623134,  0.01322267, ..., -1.44799878,
         1.53270274,  0.49569631],
       [ 0.05442056, -0.11597053, -0.10288228, ...,  0.34391584,
         0.15332546, -0.03274691],
       [-0.71343014, -1.65054799, -0.72992075, ..., -0.82181178,
         0.08295125,  1.2018417 ]])

In [2]:
import numpy as np

In [13]:
a=np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a[3]

np.int64(3)

In [6]:
a[0]

np.int64(0)

In [8]:
a[1:6]

array([1, 2, 3, 4, 5])

In [34]:
s=a[1:6].copy()

In [38]:
s

array([200, 200, 200, 200, 200])

In [39]:
a

array([  0, 200, 200, 200, 200, 200,   6,   7,   8,   9,  10])

In [40]:
a=np.arange(5)

In [41]:
a

array([0, 1, 2, 3, 4])

In [42]:
s=a[0:2].copy()
s

array([0, 1])

In [43]:
s[:]=33
s

array([33, 33])

In [44]:
a

array([0, 1, 2, 3, 4])

In [57]:
 mat=np.array([
     [1,2,4,0],
     [3,4,5,8],
     [7,8,9,1],
 ])

In [47]:
mat

array([[1, 2],
       [3, 4]])

In [48]:
mat.shape

(2, 2)

In [49]:
mat[1]

array([3, 4])

In [50]:
mat[0,1]

np.int64(2)

In [51]:
mat[1,0]

np.int64(3)

In [58]:
mat

array([[1, 2, 4, 0],
       [3, 4, 5, 8],
       [7, 8, 9, 1]])

In [59]:
mat[0:,2:]

array([[4, 0],
       [5, 8],
       [9, 1]])

In [64]:
mat.shape

(3, 4)

In [70]:
mat[1:,2:]

array([[5, 8],
       [9, 1]])

In [93]:
b=np.arange(0,5)
b

array([0, 1, 2, 3, 4])

In [73]:
b<4

array([ True,  True,  True, False, False])

In [75]:
b[b<4]

array([1, 2, 3])

In [76]:
b==2

array([False,  True, False, False, False])

In [77]:
b+b

array([ 2,  4,  6,  8, 10])

In [78]:
b-b

array([0, 0, 0, 0, 0])

In [79]:
b*b

array([ 1,  4,  9, 16, 25])

In [80]:
b/b

array([1., 1., 1., 1., 1.])

In [81]:
1/b

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [82]:
b[2]=5

In [83]:
b

array([1, 2, 5, 4, 5])

In [84]:
b[2]+b[3]

np.int64(9)

In [85]:
b[2]/b[4]

np.float64(1.0)

In [86]:
b**2

array([ 1,  4, 25, 16, 25])

In [94]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [95]:
np.exp(b)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [96]:
np.log(b)

C:\Users\nivet\AppData\Local\Temp\ipykernel_19944\4200754868.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [97]:
np.sin(b)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
a=np.arange(10,51,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
mat=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mat1=np.eye(3)
mat1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(1)

array([0.05980205])

In [17]:
np.random.randn(25)

array([ 1.38263788,  0.41258467, -0.86488423,  1.00630976,  0.39282297,
       -0.76623895,  0.44516192,  0.90018049, -0.18619088, -0.2767995 ,
       -0.64791144, -0.31843484, -0.60395279, -0.04382849,  0.26476325,
        0.62510917, -0.39323011,  1.93508334, -0.93253911,  0.20857396,
       -0.23827214,  0.6409891 , -1.46426517, -0.48777402,  0.23905631])

In [18]:
np.arange(1,101)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [31]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [44]:
mat[:3,1:2]


array([[ 2],
       [ 7],
       [12]])

In [47]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [51]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
mat+mat

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [53]:
mat[0:,0:]+mat[0:,0:]

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [54]:
mat.sum()

np.int64(325)

In [65]:
mat.var()

np.float64(52.0)

In [64]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
!pip install pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a=['Nivetha','Mariyappan']

In [ ]:
pd.series(a)

In [1]:
!pip install pandas


[notice] A new release of pip is available: 23.1.2 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import pandas as pd

In [43]:
S=['Lotus','rose','jasmine','lavender']
src1=pd.Series(S,index=[20,30,35,15])
src

25       Lotus
30        rose
35     jasmine
40    lavender
dtype: object

In [44]:
S1=['Lotus','rose','jasmine','lavender']
src2=pd.Series(S1,index=[25,30,35,40])
src

25       Lotus
30        rose
35     jasmine
40    lavender
dtype: object

In [45]:
src1+src2

15               NaN
20               NaN
25               NaN
30          roserose
35    jasminejasmine
40               NaN
dtype: object

In [49]:
sales1=[1000,2000,3000,4000]
series=pd.Series(sales1,index=['Kurti','Dupatta','Salwar','Jeans'])
series

Kurti      1000
Dupatta    2000
Salwar     3000
Jeans      4000
dtype: int64

In [50]:
sales2=[2000,1000,450,890]
series1=pd.Series(sales2,index=['Kurti','Dupatta','tshirt','Jeans'])
series1

Kurti      2000
Dupatta    1000
tshirt      450
Jeans       890
dtype: int64

In [51]:
series+series1

Dupatta    3000.0
Jeans      4890.0
Kurti      3000.0
Salwar        NaN
tshirt        NaN
dtype: float64

In [75]:
from numpy.random import randn
df=pd.DataFrame(randn(7,7),index='a b c d e f g'.split(),columns='p q r s t u v'.split())


In [81]:
df['w']=df['p']+df['q']

In [82]:
df['w']

a    1.337256
b   -1.726647
c   -2.065203
d    1.603388
e   -0.019801
f   -0.686119
g   -0.172395
Name: w, dtype: float64

In [83]:
df

p         q         r         s         t         u         v  \
a  1.490506 -0.153250  0.004216  0.379883 -1.060071  1.223254 -0.683340   
b -0.529868 -1.196778 -0.191913 -1.098874  0.225637  0.976600  0.569442   
c -0.633791 -1.431412 -0.086886 -3.270600  0.132836  1.689888 -0.291030   
d  1.748662 -0.145274  0.765169 -0.587188  0.534521  0.313343 -1.749914   
e -0.206086  0.186285  0.731942 -0.350896  0.283278  0.760982  0.773269   
f -0.342046 -0.344074 -0.570626 -0.125201  0.803104  0.842672  0.235309   
g  1.180362 -1.352757  0.160282 -0.540290 -0.315139  0.606365  0.129273   

          w  
a  1.337256  
b -1.726647  
c -2.065203  
d  1.603388  
e -0.019801  
f -0.686119  
g -0.172395

In [87]:
df.drop('w',axis=1,inplace=True)
df

p         q         r         s         t         u         v
a  1.490506 -0.153250  0.004216  0.379883 -1.060071  1.223254 -0.683340
b -0.529868 -1.196778 -0.191913 -1.098874  0.225637  0.976600  0.569442
c -0.633791 -1.431412 -0.086886 -3.270600  0.132836  1.689888 -0.291030
d  1.748662 -0.145274  0.765169 -0.587188  0.534521  0.313343 -1.749914
e -0.206086  0.186285  0.731942 -0.350896  0.283278  0.760982  0.773269
f -0.342046 -0.344074 -0.570626 -0.125201  0.803104  0.842672  0.235309
g  1.180362 -1.352757  0.160282 -0.540290 -0.315139  0.606365  0.129273

In [94]:
df.iloc[5]

p   -0.342046
q   -0.344074
r   -0.570626
s   -0.125201
t    0.803104
u    0.842672
v    0.235309
Name: f, dtype: float64

In [97]:
df.loc[['a','d','f'],['p','r','t','v']]

p         r         t         v
a  1.490506  0.004216 -1.060071 -0.683340
d  1.748662  0.765169  0.534521 -1.749914
f -0.342046 -0.570626  0.803104  0.235309

In [98]:
df>0

p      q      r      s      t     u      v
a   True  False   True   True  False  True  False
b  False  False  False  False   True  True   True
c  False  False  False  False   True  True  False
d   True  False   True  False   True  True  False
e  False   True   True  False   True  True   True
f  False  False  False  False   True  True   True
g   True  False   True  False  False  True   True

In [100]:
df[df>0]

p         q         r         s         t         u         v
a  1.490506       NaN  0.004216  0.379883       NaN  1.223254       NaN
b       NaN       NaN       NaN       NaN  0.225637  0.976600  0.569442
c       NaN       NaN       NaN       NaN  0.132836  1.689888       NaN
d  1.748662       NaN  0.765169       NaN  0.534521  0.313343       NaN
e       NaN  0.186285  0.731942       NaN  0.283278  0.760982  0.773269
f       NaN       NaN       NaN       NaN  0.803104  0.842672  0.235309
g  1.180362       NaN  0.160282       NaN       NaN  0.606365  0.129273

In [101]:
df[df<0]

p         q         r         s         t   u         v
a       NaN -0.153250       NaN       NaN -1.060071 NaN -0.683340
b -0.529868 -1.196778 -0.191913 -1.098874       NaN NaN       NaN
c -0.633791 -1.431412 -0.086886 -3.270600       NaN NaN -0.291030
d       NaN -0.145274       NaN -0.587188       NaN NaN -1.749914
e -0.206086       NaN       NaN -0.350896       NaN NaN       NaN
f -0.342046 -0.344074 -0.570626 -0.125201       NaN NaN       NaN
g       NaN -1.352757       NaN -0.540290 -0.315139 NaN       NaN

In [105]:
df[df['p']>0]['p']

a    1.490506
d    1.748662
g    1.180362
Name: p, dtype: float64

In [108]:
df[(df['p']<0)&(df['q'])>1]

Empty DataFrame
Columns: [p, q, r, s, t, u, v]
Index: []

In [115]:

df.reset_index

<bound method DataFrame.reset_index of           p         q         r         s         t         u         v
a  1.490506 -0.153250  0.004216  0.379883 -1.060071  1.223254 -0.683340
b -0.529868 -1.196778 -0.191913 -1.098874  0.225637  0.976600  0.569442
c -0.633791 -1.431412 -0.086886 -3.270600  0.132836  1.689888 -0.291030
d  1.748662 -0.145274  0.765169 -0.587188  0.534521  0.313343 -1.749914
e -0.206086  0.186285  0.731942 -0.350896  0.283278  0.760982  0.773269
f -0.342046 -0.344074 -0.570626 -0.125201  0.803104  0.842672  0.235309
g  1.180362 -1.352757  0.160282 -0.540290 -0.315139  0.606365  0.129273>

In [117]:
out=['a1','a1','a1','a1','b1','b1','b1','b1']
inside=[1,2,3,4,1,2,3,4]
hier_index=list(zip(out,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [118]:
hier_index

MultiIndex([('a1', 1),
            ('a1', 2),
            ('a1', 3),
            ('a1', 4),
            ('b1', 1),
            ('b1', 2),
            ('b1', 3),
            ('b1', 4)],
           )

In [121]:
df=pd.DataFrame(np.random.randn(8,4),index=hier_index,columns=['a','b','c','d'])

In [145]:
df.fillna(value='##')

A    B  C
0  1.0  3.0  1
1  2.0   ##  2
2   ##  8.0  3
3   ##  3.0  5

In [164]:
df.dropna(axis=1)
            

C
0  1
1  2
2  3
3  5

In [166]:
df['A'].fillna(value=df['C'].mean())

0    1.00
1    2.00
2    2.75
3    2.75
Name: A, dtype: float64

In [165]:
df

A    B  C
0  1.0  3.0  1
1  2.0  NaN  2
2  NaN  8.0  3
3  NaN  3.0  5

In [2]:
import numpy as np
import pandas as pd

In [18]:
data=({'Company':['GOOG','GOOG','MSFT','MSTF','FB','FB'],
                 'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
                 'Sales':[200,120,340,124,243,350]})
df=pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSTF  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [28]:
df.groupby('Sales').min()

Company   Person
Sales                 
120      GOOG  Charlie
124      MSTF  Vanessa
200      GOOG      Sam
243        FB     Carl
340      MSFT      Amy
350        FB    Sarah

In [1]:
import pandas as pd


In [41]:
df1 = pd.DataFrame({'S.No': [1,2,3],
                    'S.N': [4,5,6],
                        'chocolate': ['diary milk', '5star', 'perk'],
                        'icecream': ['arun', 'vennila', 'diary'],
                        'chips': ['lays', 'onion', 'tomato']},
                        index=[0, 1, 2])

In [42]:
df2 = pd.DataFrame({'S.No': [1,2,3],
                    'S.N': [4,5,6],
                        'chocolate': ['eclairs', 'dolphin', 'banana'],
                        'icecream': ['chocobar', 'strawberry', 'bites'],
                        'chips': ['greenlays', 'potato lays', 'banana chips']},
                        index=[3, 4, 5])

In [29]:
df1

S.No   chocolate icecream   chips
0     1  diary milk     arun    lays
1     2       5star  vennila   onion
2     3        perk    diary  tomato

In [30]:
df2

S.No chocolate    icecream         chips
3     1   eclairs    chocobar     greenlays
4     2   dolphin  strawberry   potato lays
5     3    banana       bites  banana chips

In [31]:
pd.concat([df1,df2])

S.No   chocolate    icecream         chips
0     1  diary milk        arun          lays
1     2       5star     vennila         onion
2     3        perk       diary        tomato
3     1     eclairs    chocobar     greenlays
4     2     dolphin  strawberry   potato lays
5     3      banana       bites  banana chips

In [32]:
pd.merge(df1,df2,how='inner',on='S.No')

S.No chocolate_x icecream_x chips_x chocolate_y  icecream_y       chips_y
0     1  diary milk       arun    lays     eclairs    chocobar     greenlays
1     2       5star    vennila   onion     dolphin  strawberry   potato lays
2     3        perk      diary  tomato      banana       bites  banana chips

In [38]:
pd.merge(df1,df2,on=['S.No','S.N'])

S.No  S.N chocolate_x icecream_x chips_x chocolate_y  icecream_y  \
0     1    4  diary milk       arun    lays     eclairs    chocobar   
1     2    5       5star    vennila   onion     dolphin  strawberry   
2     3    6        perk      diary  tomato      banana       bites   

        chips_y  
0     greenlays  
1   potato lays  
2  banana chips

In [43]:
pd.merge(df1,df2,how='right',on=['S.No','S.N'])

S.No  S.N chocolate_x icecream_x chips_x chocolate_y  icecream_y  \
0     1    4  diary milk       arun    lays     eclairs    chocobar   
1     2    5       5star    vennila   onion     dolphin  strawberry   
2     3    6        perk      diary  tomato      banana       bites   

        chips_y  
0     greenlays  
1   potato lays  
2  banana chips

In [66]:
df = pd.DataFrame({'Date':[26,27,28,29],
                   'Kurti': [5,7,8,5],
                        'shirt': [40,40,60,40],
                        'Jeans': [2,7,10,5]},
                        index=[0, 1, 2,3])

In [67]:
df

Date  Kurti  shirt  Jeans
0    26      5     40      2
1    27      7     40      7
2    28      8     60     10
3    29      5     40      5

In [62]:
df['Kurti'].unique()

array([5, 7, 8])

In [63]:
df['Kurti'].nunique()

3

In [68]:
df['shirt'].value_counts()

shirt
40    3
60    1
Name: count, dtype: int64

In [72]:
df['kurti']==2

KeyError: 'kurti'

In [3]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

In [74]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [75]:
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [78]:
def times2(x):
    return x*2

In [79]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [81]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [82]:
df['col2'].sum()

np.int64(2109)

In [84]:
del df['col1']

In [85]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [87]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [88]:
df.sort_values(by='col2')

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [89]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [90]:
df.dropna()

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [97]:
import numpy as np
df = pd.DataFrame({'col1':[1,2,3,4,np.nan],
                   'col2':[np.nan,444,555,666,444],
                   'col3':['abc','pqr','def','jkl','ghi']})


In [98]:
df

col1   col2 col3
0   1.0    NaN  abc
1   2.0  444.0  pqr
2   3.0  555.0  def
3   4.0  666.0  jkl
4   NaN  444.0  ghi

In [99]:
df.fillna('****')

col1   col2 col3
0   1.0   ****  abc
1   2.0  444.0  pqr
2   3.0  555.0  def
3   4.0  666.0  jkl
4  ****  444.0  ghi

In [4]:
df =pd.DataFrame( {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]})



In [5]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [6]:
df.pivot_table(values='D',index=['A','B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [22]:
import pandas as pd
import numpy as np

In [23]:
ls


 Volume in drive C is Windows
 Volume Serial Number is 3AFB-8EC9

 Directory of C:\Users\nivet\OneDrive\Desktop\jupyter notebook

28-06-2024  15:55    <DIR>          .
25-06-2024  15:54    <DIR>          ..
28-06-2024  15:21    <DIR>          .ipynb_checkpoints
28-06-2024  15:21                51 example.txt
28-06-2024  15:31             5,508 Excel_Sample.xlsx
28-06-2024  15:55           136,867 Numpy.ipynb
               3 File(s)        142,426 bytes
               3 Dir(s)   8,539,361,280 bytes free


In [35]:
df=pd.read_csv('example.txt')

In [25]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [33]:
pd.read_excel("Excel_sample.xlsx")

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [30]:
!pip install openpyxl


[notice] A new release of pip is available: 23.1.2 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [44]:
pd.read_html('multi_index_example.txt')

ValueError: No tables found

In [43]:
!pip install lxml

In [2]:
import pandas as pd

In [3]:
sal=pd.read_csv('Salaries.csv')

In [4]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [44]:
sal.head(3)

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2    GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3  ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN

In [45]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [54]:
sal['OvertimePay'].max()

np.float64(245131.88)

In [9]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [10]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [15]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

In [25]:
print(sal.dtypes)


Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status              float64
dtype: object


In [26]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')


In [31]:
sal['BasePay'] = sal['BasePay'].fillna('###')  # or any appropriate value
# or
sal['BasePay'] = sal['BasePay'].dropna()


In [29]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [6]:
sal.groupby('OtherPay')['TotalPay'].mean()

OtherPay
-7058.59       94215.92
-618.13         -618.13
-50.19          6882.31
-46.76         59733.32
-9.60          68968.80
                ...    
 204290.09    308694.09
 206752.00    221910.50
 245999.41    350403.41
 342802.63    471952.64
 400184.25    567595.43
Name: TotalPay, Length: 83225, dtype: float64

In [16]:
sal['JobTitle'].nunique()

2159

In [19]:
sal['JobTitle'].value_counts().head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [20]:
sal.groupby('Year')['JobTitle']

In [26]:
sal[sal['Year']==2013]['JobTitle']

72925                    Chief of Police
72926             Chief, Fire Department
72927     Battalion Chief, Fire Suppress
72928                  Asst Med Examiner
72929       Dep Dir for Investments, Ret
                       ...              
110526           PS Aide Health Services
110527                      Senior Clerk
110528                  Police Officer 3
110529                  Police Officer 3
110530                  Police Officer 3
Name: JobTitle, Length: 37606, dtype: object

In [29]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts()==1)

202

In [35]:
sal['len']=sal['JobTitle'].apply(len)

In [32]:
sal['len']

0         46
1         31
2         31
3         36
4         44
          ..
148649     9
148650    12
148651    12
148652    12
148653    26
Name: len, Length: 148654, dtype: int64

In [42]:
sal[['BasePay','OvertimePay']].corr()

BasePay  OvertimePay
BasePay      1.00000      0.26674
OvertimePay  0.26674      1.00000

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Ecommerce Purchases.txt')

In [3]:
df

Address    Lot AM or PM  \
0     16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1     9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                      Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3                 7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4     23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   
...                                                 ...    ...      ...   
9995      966 Castaneda Locks\nWest Juliafurt, CO 96415  92 XI       PM   
9996  832 Curtis Dam Suite 785\nNorth Edwardburgh, T...  41 JY       AM   
9997              Unit 4434 Box 6343\nDPO AE 28026-0283  74 Zh       AM   
9998               0096 English Rest\nRoystad, IA 12457  74 cL       PM   
9999     40674 Barrett Stravenue\nGrimesville, WI 79682  64 Hr       AM   

                                           Browser Info  \
0     Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1     Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2     Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4     Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   
...                                                 ...   
9995  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...   
9996  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
9997  Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...   
9998  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...   
9999  Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...   

                              Company       Credit Card CC Exp Date  \
0                     Martinez-Herman  6011929061123406       02/20   
1     Fletcher, Richards and Whitaker  3337758169645356       11/18   
2          Simpson, Williams and Pham      675957666125       08/19   
3     Williams, Marshall and Buchanan  6011578504430710       02/24   
4           Brown, Watson and Andrews  6011456623207998       10/25   
...                               ...               ...         ...   
9995                    Randall-Sloan   342945015358701       03/22   
9996         Hale, Collins and Wilson   210033169205009       07/25   
9997                     Anderson Ltd  6011539787356311       05/21   
9998                         Cook Inc   180003348082930       11/17   
9999                       Greene Inc  4139972901927273       02/19   

      CC Security Code                  CC Provider  \
0                  900                 JCB 16 digit   
1                  561                   Mastercard   
2                  699                 JCB 16 digit   
3                  384                     Discover   
4                  678  Diners Club / Carte Blanche   
...                ...                          ...   
9995               838                 JCB 15 digit   
9996               207                 JCB 16 digit   
9997                 1                VISA 16 digit   
9998               987             American Express   
9999               302                 JCB 15 digit   

                               Email                                     Job  \
0                  pdunlap@yahoo.com  Scientist, product/process development   
1                 anthony41@reed.com                       Drilling engineer   
2     amymiller@morales-harrison.com                Customer service manager   
3        brent16@olson-robinson.info                       Drilling engineer   
4        christopherwright@gmail.com                             Fine artist   
...                              ...                                     ...   
9995          iscott@wade-garner.com                              Printmaker   
9996              mary85@hotmail.com                         Energy engineer   
9997               tyler16@gmail.com                      Veterinary surgeon   
9998         elizabethmoore@reid.net                Local government officer   
9999           rachelford@vaughn.com        

In [4]:
df.head(4)

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   

   CC Security Code   CC Provider                           Email  \
0               900  JCB 16 digit               pdunlap@yahoo.com   
1               561    Mastercard              anthony41@reed.com   
2               699  JCB 16 digit  amymiller@morales-harrison.com   
3               384      Discover     brent16@olson-robinson.info   

                                      Job       IP Address Language  \
0  Scientist, product/process development  149.146.147.205       el   
1                       Drilling engineer     15.160.41.51       fr   
2                Customer service manager   132.207.160.22       de   
3                       Drilling engineer     30.250.74.19       es   

   Purchase Price  
0           98.14  
1           70.73  
2            0.95  
3           78.04

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [6]:
df['Purchase Price'].mean()

np.float64(50.347302)

In [7]:
df['Purchase Price'].max()

np.float64(99.99)

In [8]:
df['Purchase Price'].min()

np.float64(0.0)

In [11]:
df[df['Language']=='en'].count()

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64

In [12]:
df[df['Job']=='Lawyer'].count()

Address             30
Lot                 30
AM or PM            30
Browser Info        30
Company             30
Credit Card         30
CC Exp Date         30
CC Security Code    30
CC Provider         30
Email               30
Job                 30
IP Address          30
Language            30
Purchase Price      30
dtype: int64

In [14]:
df['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

In [22]:
df['Job'].value_counts().head(5)

Job
Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Designer, jewellery                  27
Research officer, political party    27
Name: count, dtype: int64

In [29]:
df[df['Lot']=='90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

In [30]:
df

Address    Lot AM or PM  \
0     16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1     9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                      Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3                 7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4     23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   
...                                                 ...    ...      ...   
9995      966 Castaneda Locks\nWest Juliafurt, CO 96415  92 XI       PM   
9996  832 Curtis Dam Suite 785\nNorth Edwardburgh, T...  41 JY       AM   
9997              Unit 4434 Box 6343\nDPO AE 28026-0283  74 Zh       AM   
9998               0096 English Rest\nRoystad, IA 12457  74 cL       PM   
9999     40674 Barrett Stravenue\nGrimesville, WI 79682  64 Hr       AM   

                                           Browser Info  \
0     Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1     Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2     Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4     Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   
...                                                 ...   
9995  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...   
9996  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
9997  Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...   
9998  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...   
9999  Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...   

                              Company       Credit Card CC Exp Date  \
0                     Martinez-Herman  6011929061123406       02/20   
1     Fletcher, Richards and Whitaker  3337758169645356       11/18   
2          Simpson, Williams and Pham      675957666125       08/19   
3     Williams, Marshall and Buchanan  6011578504430710       02/24   
4           Brown, Watson and Andrews  6011456623207998       10/25   
...                               ...               ...         ...   
9995                    Randall-Sloan   342945015358701       03/22   
9996         Hale, Collins and Wilson   210033169205009       07/25   
9997                     Anderson Ltd  6011539787356311       05/21   
9998                         Cook Inc   180003348082930       11/17   
9999                       Greene Inc  4139972901927273       02/19   

      CC Security Code                  CC Provider  \
0                  900                 JCB 16 digit   
1                  561                   Mastercard   
2                  699                 JCB 16 digit   
3                  384                     Discover   
4                  678  Diners Club / Carte Blanche   
...                ...                          ...   
9995               838                 JCB 15 digit   
9996               207                 JCB 16 digit   
9997                 1                VISA 16 digit   
9998               987             American Express   
9999               302                 JCB 15 digit   

                               Email                                     Job  \
0                  pdunlap@yahoo.com  Scientist, product/process development   
1                 anthony41@reed.com                       Drilling engineer   
2     amymiller@morales-harrison.com                Customer service manager   
3        brent16@olson-robinson.info                       Drilling engineer   
4        christopherwright@gmail.com                             Fine artist   
...                              ...                                     ...   
9995          iscott@wade-garner.com                              Printmaker   
9996              mary85@hotmail.com                         Energy engineer   
9997               tyler16@gmail.com                      Veterinary surgeon   
9998         elizabethmoore@reid.net                Local government officer   
9999           rachelford@vaughn.com        

In [36]:
df[df['Credit Card']==4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [41]:
df[(df['CC Provider']=='Amercican Express')&(df['Purchase Price']>95)].count()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

In [46]:
df[df['CC Exp Date']==2025]['Credit Card'].count()

np.int64(0)